# Generated by Django 4.2.6 on 2023-11-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='createdAt',
            new_name='createAt',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
